### PR TITLE
fix / revised uniswap-base support

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
[c8e092b](https://github.com/hummingbot/gateway/pull/329/commits/c8e092b3049efe6660c72180db72594c20004028)
Steps:
1. Clone latest development branch + gwPR329
2. connect uniswap ethereum base
3. check balance succesfully
4. create amm_arb strategy using uniswap_ethereum_base and binance_paper_trade
5. start the strategy and review the error




```
2024-06-04 20:26:32,770 - 4059849 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-06-04 20:26:32,850 - 4059849 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-06-04 20:26:32,855 - 4059849 - GatewayEVMAMM - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-06-04 20:26:32,928 - 4059849 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/estimateGas failed. See logs for more details.
2024-06-04 20:26:32,930 - 4059849 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/estimateGas Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: No address for Uniswap Multicall Contract on chain id: 8453\n    at new UniswapMulticallProvider (/home/nikita/gwb329/node_modules/@uniswap/smart-order-router/build/main/providers/multicall-uniswap-provider.js:30:19)\n    at new AlphaRouter (/home/nikita/gwb329/node_modules/@uniswap/smart-order-router/build/main/routers/alpha-router/alpha-router.js:47:97)\n    at new Uniswap (/home/nikita/gwb329/dist/src/connectors/uniswap/uniswap.js:47:29)\n    at Uniswap.getInstance (/home/nikita/gwb329/dist/src/connectors/uniswap/uniswap.js:72:51)\n    at /home/nikita/gwb329/dist/src/services/connection-manager.js:132:51\n    at Generator.next (<anonymous>)\n    at /home/nikita/gwb329/dist/src/services/connection-manager.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/nikita/gwb329/dist/src/services/connection-manager.js:4:12)\n    at getConnector (/home/nikita/gwb329/dist/src/services/connection-manager.js:128:12)'}
2024-06-04 20:26:33,564 - 4059849 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-06-04 20:26:33,665 - 4059849 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for ETH-USDT. 1/1 completed.
2024-06-04 20:26:40,000 - 4059849 - hummingbot.strategy.amm_arb.amm_arb - WARNING - uniswap_ethereum_base not ready: waiting for network_transaction_fee.
2024-06-04 20:26:50,001 - 4059849 - hummingbot.strategy.amm_arb.amm_arb - WARNING - uniswap_ethereum_base not ready: waiting for network_transaction_fee.
2024-06-04 20:27:00,001 - 4059849 - hummingbot.strategy.amm_arb.amm_arb - WARNING - uniswap_ethereum_base not ready: waiting for network_transaction_fee.
2024-06-04 20:27:10,000 - 4059849 - hummingbot.strategy.amm_arb.amm_arb - WARNING - uniswap_ethereum_base not ready: waiting for network_transaction_fee.
```


[logs_conf_amm_arb_1.log](https://github.com/user-attachments/files/15570096/logs_conf_amm_arb_1.log)
[gw329.zip](https://github.com/user-attachments/files/15570102/gw329.zip)


image

**Comment by fengtality** [comment]
@nikspz This PR is ready for testing. The tests still fail, but I'm working on a fix.

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned gwPR329 with Client latest development
- gateway connect uniswap_ethereum_base successfully
- added gateway connector-tokens WETH,USDC
- gateway balance now show WETH,USDC balance
- created amm_arb strategy using uniswap ethereum base
- start amm_arb successfully
- review filled orders handling is okay with no errors
- curl:
  - wallet/add: ok 
  - amm/price: ok 
  - amm/trade: ok
- Review quipuswap removed (as not-voted per previous poll)

https://basescan.org/tx/0x16f8642137cc3b13cbcee47fb75c080c60e95dc92e965ccfe1aaaa69d7a3196e
image

image

**Comment by LautaroNavarro** [comment]
> * gateway connect uniswap_ethereum_base
I'm in the development branch on both projects, hummingbot and gateway. The command `gateway connect uniswap_ethereum_base` is not working. The error is `No available blockchain networks available for connector uniswap_ethereum_base`.
Is there something that I'm missing?

**Comment by LautaroNavarro** [comment]
I was able to connect to base sepolia but the balance being shown is not correct 
Screenshot 2024-07-26 at 13 38 59
Screenshot 2024-07-26 at 13 39 44

**Comment by fengtality** [comment]
Screenshot 2024-07-26 at 9 52 29 AM

works for me

`sepolia` is the Ethereum Sepolia testnet, not Base Sepolia. If you want to use Base Sepolia, submit a PR with the correct token list and addresses, etc

**Pull request merged**
