### PR TITLE
fix/dont use router in uniswaplp

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

* May fix https://github.com/hummingbot/gateway/issues/152

**Tips for QA testing**:

* Please run Gateway from source and test adding liquidity

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
Cloned and install: fix PR gw branch + Client - latest development branch
Created/started uniswapLP startegy using uniswap arbitrum successfully and WETH-USDC.E pair
bot returned error `One of the tokens in this position isn't recognized`
However Reviewed `liquidity added successfully` ✅
Created/started uniswapLP startegy using uniswap arbitrum successfully and WETH-ARB pair
bot returned error `One of the tokens in this position isn't recognized`
However Reviewed `liquidity added successfully` ✅

[logs_gateway_app.log](https://github.com/hummingbot/gateway/files/12024424/logs_gateway_app.log)
[logs_conf_uniswap_v3_lp_1.log](https://github.com/hummingbot/gateway/files/12024421/logs_conf_uniswap_v3_lp_1.log)
[logs_unilp2.log](https://github.com/hummingbot/gateway/files/12024423/logs_unilp2.log)
[gw153.zip](https://github.com/hummingbot/gateway/files/12024433/gw153.zip)

```
2023-07-12 05:26:13,712 - 218157 - GatewayEVMAMMLP - INFO - Created ADD liquidity order add-WETH-USDC.E-1689139570209342 txHash: 0x3e7c326316df003591835b6ef0a9e39fb29efbcb51f064ce198bca9775a25d86 on arbitrum_one. Estimated Gas Cost: 0.000015069000000000  (gas limit: 3000000, gas price: 0.1000000000000000055511151231257827021181583404541015625)
2023-07-12 05:26:13,713 - 218157 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1689139573.0, "order_id": "add-WETH-USDC.E-1689139570209342", "exchange_order_id": "0x3e7c326316df003591835b6ef0a9e39fb29efbcb51f064ce198bca9775a25d86", "order_action": "LPType.ADD", "trading_pair": "WETH-USDC.E", "fee_tier": "LOW", "lower_price": "1790.288903791500000", "upper_price": "1978.740367348500000", "amount": "0.005000", "creation_timestamp": 1689139570.0, "token_id": 0, "event_name": "RangePositionUpdateEvent", "event_source": "uniswapLP_ethereum_arbitrum_one"}
2023-07-12 05:26:14,265 - 218157 - GatewayEVMAMMLP - INFO - Liquidity added for position with ID 719713.
2023-07-12 05:26:14,275 - 218157 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1689139574.0, "order_id": "add-WETH-USDC.E-1689139570209342", "exchange_order_id": "0x3e7c326316df003591835b6ef0a9e39fb29efbcb51f064ce198bca9775a25d86", "trading_pair": "WETH-USDC.E", "lower_price": "1790.288903791500000", "upper_price": "1978.740367348500000", "amount": "0", "fee_tier": "LOW", "creation_timestamp": 1689139570.0, "trade_fee": {"percent": "0", "percent_token": null, "flat_fees": [{"token": "ETH", "amount": "0.0001003772000000000055720539294"}]}, "token_id": 719713, "event_name": "RangePositionLiquidityAddedEvent", "event_source": "uniswapLP_ethereum_arbitrum_one"}
2023-07-12 05:26:15,214 - 218157 - GatewayEVMAMMLP - ERROR - Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
Traceback (most recent call last):
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 1097, in _status_polling_loop
    await safe_gather(
  File "/home/nikita/development/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 970, in update_nft
    raise nft_update_result
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 798, in amm_lp_position
    return await self.api_request("post", "amm/liquidity/position", request_payload)
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2023-07-12 05:26:16,207 - 218157 - GatewayEVMAMMLP - ERROR - Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
Traceback (most recent call last):
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 1097, in _status_polling_loop
    await safe_gather(
  File "/home/nikita/development/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 970, in update_nft
    raise nft_update_result
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 798, in amm_lp_position
    return await self.api_request("post", "amm/liquidity/position", request_payload)
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2023-07-12 05:26:17,191 - 218157 - GatewayEVMAMMLP - ERROR - Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
Traceback (most recent call last):
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 1097, in _status_polling_loop
    await safe_gather(
  File "/home/nikita/development/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/nikita/development/hummingbot/connector/gateway/amm_lp/gateway_evm_amm_lp.py", line 970, in update_nft
    raise nft_update_result
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 798, in amm_lp_position
    return await self.api_request("post", "amm/liquidity/position", request_payload)
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/nikita/development/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/amm/liquidity/position Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "Error: One of the tokens in this position isn't recognized.\n    at UniswapLP.<anonymous> (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:76:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/nikita/gwfixlp/dist/src/connectors/uniswap/uniswap.lp.js:28:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
```

image
image

**Comment by emusol** [comment]
Wow thats good! will this fix also remove liquidity?

**Comment by nikspz** [comment]
Bot Client do not have this feature currently @emusol

**Comment by emusol** [comment]
> Bot Client do not have feature to remove liquidity from UniswapLP currently @emusol

gateway had this functionality, I have custom script utilizing it successfully before the issue with uniswaplp started

**Comment by nikspz** [comment]
@emusol Could you please share the script for further testing?

**Comment by nikspz** [comment]
Tried to remove with curl command:

### remove liquidity
```
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/eth_uniswap_position.json)" https://localhost:15888/amm/liquidity/remove | jq
```
Got same issue: One of the tokens in this position isn't recognized
image

**Comment by nikspz** [comment]
Created issue for removing liquidity as it also exist for the latest development branch
https://github.com/hummingbot/gateway/issues/154

**Review by nikspz — APPROVED** [review]

**Pull request merged**
