### PR TITLE
(fix) Adds case-sensitive trading pairs handling for Dexalot

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR adds handling of case-sensitive trading pairs to the Dexalot connector.

**Tests performed by the developer**:

- Adapted the unit tests to catch this issue in the future.
- Manually tested the bot using BTC.B-USDC (exchange pair BTC.b/USDC).

**Tips for QA testing**:

Please ensure that case sensitive trading pairs don't cause problems for the bot.

### CODE REVIEW

**Comment by nikspz** [comment]
hi @petioptrv 

Tests performed:

- Clone and install development + gatewayPR80
- start the bot and gatewayPR80
- add balance for BTC.b and WETH.e
- added gateway connector-tokens dexalot_avalanche_dexalot BTC.B,WETH.E
- checked that bot shows correct balance for WETH.E and `incorrect for BTC.B`
- created pureMM startegy using BTC.B-USDC and WETH.E-USDC
- review that bot do not placed the orders for BTC.B-USDC and also for WETH.E-USDC Pair



Currently `there're issues on the PR`
1. Bot `Not displayed BTC.B balance` using Client and also using 
2. endpoint does not display also used {BTC.b, BTC.B} but still its showing 0.000000
3. Bot `Doesn't place orders` using `BTC.B-USDC` market
4. Bot `Doesn't place orders` using `WETH.E-USDC` market

1.) 
Steps to reproduce:

- add/swap to have BTC.b balance on the exchange
- check balance on the client
- Pay attention to BTC.B balance on the Client

image

2.)
Same thing using endpoints
image

3.)
BTC.B-USDC market bot failed to place orders

image



4)
WETH.E-USDC market bot failed to place orders

image

**Comment by petioptrv** [comment]
@nikspz, thank you for testing. I have pushed a fix for the balance issue observed here in the last commit ([ed335b2](https://github.com/hummingbot/gateway/pull/80/commits/ed335b2c11c31c742c90bca4c0f39abf94b2047c)). The order placement issue is due to a problem in the trading rules parsing, and I've added a fix for that on the client side in [this PR](https://github.com/hummingbot/hummingbot/pull/6188). The PR is still in draft mode as I am giving the Dexalot team a chance to test out the new rate limits configuration before I commit to that setting.

**Review by nikspz — DISMISSED** [review]
Tests performed:

- Clone and install PR 6191+ gatewayPR80
- start the bot and gatewayPR80
- add balance for BTC.b and WETH.e
- added gateway connector-tokens dexalot_avalanche_dexalot BTC.B,WETH.E
- checked that bot shows correct balance for WETH.E and for BTC.B
- created pureMM/amm_arb startegy using BTC.B-USDC and WETH.E-USDC
- review that bot placed the orders for BTC.B-USDC, WETH.E-USDC and AVAX-USDC Pair

**Review by nikspz — APPROVED** [review]
Tests performed:

- Clone and install PR 6191+ gatewayPR80
- start the bot and gatewayPR80
- add balance for BTC.b and WETH.e
- added gateway connector-tokens dexalot_avalanche_dexalot BTC.B,WETH.E
- checked that bot shows correct balance for WETH.E and for BTC.B
- created pureMM/amm_arb startegy using BTC.B-USDC and WETH.E-USDC
- review that bot placed the orders for BTC.B-USDC, WETH.E-USDC and AVAX-USDC Pair

**Review by fengtality — APPROVED** [review]

**Pull request merged**
