### PR TITLE
feat/ add base network

### PR DESCRIPTION
**Pull request by LautaroNavarro**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add base network, and mainnet + sepolia chains

**Tests performed by the developer**:
* Tested creating a connection using uniswap connect + network base + chain mainnet
* Tested creating a connection using uniswap connect + network base + chain sepolia
* Tested getting the balance for mainnet wallet
* Tested getting the balance for sepolia wallet
Screenshot 2024-07-23 at 16 21 49
Screenshot 2024-07-23 at 16 15 22

**Tips for QA testing**:
To test this with the hummingbot client you will need to add the base network to the native_tokens list in the gateway_config_utils.py file. (Inside of the hummingbot repository, and not the gateway repository)

### CODE REVIEW

**Comment by LautaroNavarro** [comment]
@fengtality can you approve the workflow run?

**Comment by fengtality** [comment]
@LautaroNavarro I don't think Base should be a separate chain, but rather a Ethereum L2 network, like Arbitrum and Optimism. There's actually a separate Gateway PR for Base support: https://github.com/hummingbot/gateway/pull/329

I'll take a look at your changes and see what I can add

**Comment by fengtality** [comment]
Closing in favor of https://github.com/hummingbot/gateway/pull/329.

Rationale:
- Base should be added as an Ethereum network, not a new chain
- Base token lists included in this PR are wrong

**Comment by LautaroNavarro** [comment]
@fengtality thanks! Yes, adding base as an Ethereum network make sense since it's a L2. About the tokens, I'm not really sure where do you get the list from, I went to uniswap and took them from the requests.
Do you have an ETA for #329 ?

**Pull request closed without merging**
