### PR TITLE
Feat/pancake swap v3

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Add LP to Pancakeswap

**Tests performed by the developer**:
- Curl test
- Unit test
- End-to-end testing with uniswapLp strategy on the client

**Tips for QA testing**:
- Test as you would test uniswapLP, but replacing chain with `binance-smart-chain` and network with `mainnet`.

### CODE REVIEW

**Comment by vic-en** [comment]
@fengtality I'll do that soon.
Curious to know what issue it caused.
I noticed that change when I updated the typescript version inthe package.json file which is required by the pancake dependency.

**Comment by vic-en** [comment]
@fengtality @nikspz @rapcmia 
I updated the yarn lock. Review can continue.

**Review by rapcmia — APPROVED** [review]
- Setup this PR with latest development client
- Pancakeswap LP must be tested on BSC mainnet
- API test using Thunderclient
    - GET/port ok
    - GET/Wallet ok
    - POST/add ok
    - GET/connectors ok
- API test using Curl
    - `curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT https://localhost:15888/ | jq` ok
    - `curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT https://localhost:15888/chain/status | jq` ok
    - `curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/add_bsc_key.json)" https://localhost:15888/wallet/add | jq` ok
    - `curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/bsc_balances.json)" https://localhost:15888/chain/balances | jq` ok
    - `curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/eth_uniswap_add_liquidity.json)" https://localhost:15888/amm/liquidity/add | jq` ok 
    - `curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/eth_uniswap_position.json)" https://localhost:15888/amm/liquidity/remove | jq` ok

---

Ran tests using uniswap_v3_lp
- Token approved for WBNB and CAKE
- Liquidity added on position successfully
   image
   - When a position is closed, strategy proceeds with creating one again
   - Stop strategy and start again, retrieve the active position from pancakeswapLP
   - Stop and exit the client. Open, import and start strategy, successfully retrieved position with exact ID

**Comment by rapcmia** [comment]
Hi @vic-en github checks are still failing after 3/3 reruns 🙇🏼

**Comment by vic-en** [comment]
@rapcmia I'm still finding a good solution to the issue causing the workflow to fail.
I'll let you know as soon as I have something that works.
Thanks.

**Review by fengtality — APPROVED** [review]

**Comment by fengtality** [comment]
@vic-en Don't worry about the workflow issues, as they appear to be related to the XRP chain and connector. I'll exclude them from the standard tests.

**Comment by jellebuth** [comment]
I ran a test for fetching the trading prices of a pool and the new codebase does not seem to fetch the prices from a V3 pool correctly. 

Steps to replicate:
1. Set UseRouter -> True
2. Fetch price of ARV/WBNB pool for 1 ARV
3. Compare price with Pancakeswap interface (this should show a difference) 
4. Customise the routing on Pancakeswap to only include V2 pools
image

image
5. Fetch price of ARV/WBNB pool for 1 ARV
6. Compare prices between PCS interface and Gateway price response (this should show a minimal difference) 

Am I missing any steps in retrieving V3 prices compared to only V2 prices of a token?

**Comment by nikspz** [comment]
@jellebuth 
Changed rate_oracle_source to gate_io, seems able to get the price

image

image
image

**Comment by jellebuth** [comment]
@nikspz 

I was trying to get it for RITE (which only has a V3 Pool. But it returns that there is no pool for RITE. 

https://www.geckoterminal.com/bsc/pools/0x9b36e5b07eab82cd861aeb282235b95ee029164d

I think that the price fetching feature does not have a V3 integration yet? If I look at the source code, it seems like the function that returns the price does not follow similar logic as the one for Uniswap (which does have a V3 integration). 

But I might be wrong in this.

**Comment by nikspz** [comment]
> I was trying to get it for RITE (which only has a V3 Pool. But it returns that there is no pool for RITE.

To triage the issue, Could you confirm are you're using LP strategy? or requests?
Could you please attach log/ config file as well?

**Comment by vic-en** [comment]
@jellebuth @nikspz 
0x0F5D54b27bDb556823F96f2536496550f8816dC5, which is the token address  for RITE isn't in the default Bsc mainnet token list(https://github.com/hummingbot/gateway/blob/main/src/templates/lists/bep20_tokens_mainnet.json).

So add the token and the issue shouldn't persist.

**Comment by jellebuth** [comment]
@vic-en @nikspz I have added this one already, but the issue persists. 

@vic-en can you confirm that the V3 smart order router for price fetching is correctly integrated? And whether you are able to get the prices for the RITE-USDT V3 pool?

**Comment by vic-en** [comment]
I'll do that.
BTW what fee tier are you using?
@jellebuth

**Pull request merged**
