### PR TITLE
Feat/openocean updates

### PR DESCRIPTION
**Pull request by onjeffery**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
openocean add bsc,cronos,arbitrum and optimism chains

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by onjeffery** [comment]
> Hi @onjeffery thanks for submitting this PR, please also add a thread on our `proposal-discussions` and info about it on discord so the community is aware and cast votes for the snapshot. Thank you
> 
> image

ok created

**Review by fengtality — APPROVED** [review]
LGTM

Please submit changes to OpenOcean page in docs: https://github.com/hummingbot/hummingbot-site/blob/main/docs/exchanges/openocean.md

**Comment by nikspz** [comment]
Failed to do initial token approval using openocean_binance-smart-chain_mainnet

Steps: 
Approve tokens on the exchange/bot side
Create/start amm_arb strategy using openocean_binance-smart-chain_mainnet

Actual:
Failed to start strategy, bot stuck into  `openocean_binance-smart-chain_mainnet not ready: waiting for allowances: use trading interface to do manual approval..`

Expected: 
Bot use token that approved manually on metamask and calculate profitability 

image
image






Same wallet using sushiswap_binance-smart-chain_mainnet

image
image

**Comment by rapcmia** [comment]
PR update:
- Run endpoint tests using thunder client 
- Port, wallet {add, remove}, balances and poll all ok ✅ 

However for arbitrum and optimism we are not able to proceed with `allowance `and `approve `endpoints and getting the same behavior reported above. While the previous commend shows issue on binance-smart-chain, we are able to run the endpoints without any issues at the moment

Arbitrum one
image

Optimism
image

**Pull request merged**
