### PR TITLE
Uniswap - add avalanche chain/network to the current Uniswap connector

### PR DESCRIPTION
**Pull request by isreallee82**
Before submitting this PR, please make sure:

 Your code builds clean without any errors or warnings
 You are using approved title ("feat/", "fix/", "docs/", "refactor/")
A description of the changes proposed in the pull request:

Tests performed by the developer:
Test performed:

Set up gateway successfully
connected uniswap ethereum Avalanche successfully
check wallet now showing on gateway connect command
check gateway balance show balance for the ethereum cello wallet

curl test

 chain/status: ok
 /chain/balances: ok
 /chain/allowance: ok
 add/ remove wallet: ok
 /amm/price: ok

Tips for QA testing:

### CODE REVIEW

**Comment by nikspz** [comment]
> Set up gateway successfully connected uniswap ethereum Avalanche 

Hmm I think It should be `uniswap_avalanche_avalanche`, since Avalanche is chain and network (separate from ethereum chain)

**Comment by isreallee82** [comment]
Either ways Avalanche is EVM compatible... in this context it should still work as expected. Made modifications to use Avalanche chain instead @nikspz

**Comment by isreallee82** [comment]
made a clean-up @nikspz it should be good for a review now

**Comment by isreallee82** [comment]
Just a reminder if there is anything more I needed to do here @nikspz

**Comment by fengtality** [comment]
Incorporated into https://github.com/hummingbot/gateway/pull/342

**Pull request closed without merging**
