### PR TITLE
feat/solana-connector

### PR DESCRIPTION
**Pull request by fengtality**
**A description of the changes proposed in the pull request**:

This is an ongoing PR to add back the Solana chain connector, along with a future Raydium connector.

### CODE REVIEW

**Comment by gelinger777** [comment]
how can we test it ?

**Comment by fengtality** [comment]
> how can we test it ?

Use it with Postman as described here https://hummingbot.org/gateway/testing/#testing-with-postman

Currently working are the basic chain endpoints for fetching balances, etc

**Comment by gelinger777** [comment]
> > how can we test it ?
> 
> 
> 
> Use it with Postman as described here https://hummingbot.org/gateway/testing/#testing-with-postman
> 
> 
> 
> Currently working are the basic chain endpoints for fetching balances, etc

So we cant rely on it to fetch data for at least backtesting?

**Comment by gelinger777** [comment]
@fengtality  is it now available to build  market making bots on solana?

**Comment by gelinger777** [comment]
@fengtality  is it possible to  use like 30 wallets in market making logic instead of one ?

**Comment by Denni-Wild** [comment]
> > > how can we test it ?
> > 
> > 
> > Use it with Postman as described here https://hummingbot.org/gateway/testing/#testing-with-postman
> > Currently working are the basic chain endpoints for fetching balances, etc
> 
> So we cant rely on it to fetch data for at least backtesting?

I am on the same way - fetch data for backtesting with Solana ..
Doing periodic requests now to fill in own db 
a temporary solution, but its better than nothing
 solana connectors will be best , but later
 Are you researching same situation?

**Comment by gelinger777** [comment]
@Denni-Wild   yes,  I want also to build a MM bot .

**Pull request closed without merging**
