### PR TITLE
feat/Interact directly with the pool in Uniswap connector

### PR DESCRIPTION
**Pull request by VPashkov**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds the ability to use [Quoter](https://docs.uniswap.org/contracts/v3/reference/periphery/lens/QuoterV2) rather than [Smart Order Router](https://github.com/Uniswap/smart-order-router) to the Uniswap connector as an option.
To achieve this `uniswap.yml` config file is extended with the following:
- `useRouter` (bool, default=true) - if True, estimation and execution functions use the Router; if false, use quote and trade functions of SDK.
- `feeTier` (string, default='MEDIUM') - Matches one of the Uniswap fee tier strings. If useRouter is False, then the user has to specify feeTier to find the right pool.
- `uniswapV3QuoterV2ContractAddress` (string) - a variable added to each network in `contractAddresses` section. Stores the address of Uniswap Quoter V2. It can be found here https://docs.uniswap.org/contracts/v3/reference/deployments.

**Tests performed by the developer**:
- Requests to get price and to execute trade sent using examples from `test-helpers/curl/curl.sh`. E.g.:
```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./test-helpers/curl/requests/price_uniswap.json)" https://localhost:15888/amm/price | jq
```
- Checked that prices returned by the Quoter are the same(or very close) as those returned by the Router when using the same fee tier.
- Checked that executing trades(`/amm/trade`) works with the Quoter.

**Tips for QA testing**:
- Sometimes price returned using the Router is different than using the Quoter. This is usually due to a different fee tier. Try a different value for `feeTier` variable in `uniswap.yml` config file to get the same price.

### CODE REVIEW

**Comment by VPashkov** [comment]
Resolves #112

**Comment by toxicehc** [comment]
Hi @VPashkov , how would I test this on a HB/gateway instance running from source? The production version of the gateway is no longer able to get prices from Uniswap as of some days ago..

**Review by fengtality — APPROVED** [review]
LGTM

* Reviewed code - looks clean
* Tested on Goerli - buy and sell trades worked
* Ran tests successfully

Thanks for the contribution!

**Comment by emusol** [comment]
Hey this seems to not solve the LP side of uniswap, maybe similar udpate to the code can help?

**Comment by nikspz** [comment]
https://github.com/hummingbot/gateway/issues/152 Created issue for UniswapLP

**Pull request merged**
