### PR TITLE
Feat/tinyman

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
[ch 39263]
This pr adds the tiny man connector on top of the Algorand chain.

**Tests performed by the developer**:
- Price endpoint test
- Trade endpoint test

**Tips for QA testing**:
- Test price endpoint using curl
- Test trade endpoint using curl

Algorand generic connector - https://github.com/hummingbot/hummingbot/pull/6277
PRP - https://snapshot.org/#/hbot-prp.eth/proposal/0x08a53dead66043ee8e8b0e65229a99b52be2e212a640e992eb72c9b4cd388701

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test on local WSL ubuntu20.04 with https://github.com/hummingbot/hummingbot/pull/6277
- Connect successfully wallet using `Pera wallet` and balance displayed ok 
- Setup thunder client for postman related tests {port, connectors}
- Ran test endpoints using curl
   - Port and connectors ✅ 
   - Add/Remove wallet ✅ 
   - Get balance ✅ 
   - Get poll ✅ 
   - Get assets ✅
   - Post opt-in {GALGO,USDC} ✅  
   - Check prices ✅ 
   - Trade {BUY,SELL} ✅ 
      - Compare trade data from endpoint and txhash from https://algoexplorer.io/
      - If not enough balance, getting error of `overspend` both client and gateway logs 
      
 Pending:
 - Client + Gateway test with connector

**Review by rapcmia — APPROVED** [review]

**Review by fengtality — DISMISSED** [review]

**Comment by nikspz** [comment]
@vic-en 
Failed to yarn build on this PR:

Steps:
1. git clone -b feat/tinyman https://github.com/CoinAlpha/gateway.git gw90
2. cd gw90
3. yarn && yarn build

Actual:
Found 1 error in src/connectors/connectors.routes.ts:146
error Command failed with exit code 2.

```
src/connectors/connectors.routes.ts:146:13 - error TS2322: Type '{ name: string; trading_type: string[]; chain_type: string; available_networks: AvailableN
etworks[]; }' is not assignable to type '{ name: string; trading_type: string[]; available_networks: AvailableNetworks[]; additional_spenders?: string[] |
undefined; additional_add_wallet_prompts?: Record<string, string> | undefined; }'.
  Object literal may only specify known properties, and 'chain_type' does not exist in type '{ name: string; trading_type: string[]; available_networks: Av
ailableNetworks[]; additional_spenders?: string[] | undefined; additional_add_wallet_prompts?: Record<string, string> | undefined; }'.

146             chain_type: TinymanConfig.config.chainType,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/connectors/connectors.routes.ts:146

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
image

**Comment by vic-en** [comment]
@nikspz PR #105 needs to be merged first.

**Comment by nikspz** [comment]
@vic-en yes, it merged

**Comment by vic-en** [comment]
Pull again. I just merged with development on this pr.

**Comment by nikspz** [comment]
Test performed:
- Test on local WSL ubuntu20.04 with https://github.com/hummingbot/hummingbot/pull/6277
- Connect successfully wallet using `Pera wallet` seed phrase, correct balance displayed
- Added connector-tokens goBTC, balance not displayed after that (reported in comment above)
- Ran test endpoints using curl
   - Status and /connectors ✅ 
   - /network/status?chain=algorand ✅ 
   - /wallet/add and /wallet/remove ✅ 
   - Get balance ✅ Failed to get balance for goBTC ❌
   - Get poll ✅ 
   - Get assets ✅
   - Post opt-in {GALGO,USDC} ✅  
   - Check prices ✅ Failed to check price for `ALGO-USDt` using USDt with lowerkey letter ❌
   - Trade {BUY,SELL} ✅ 
      - Compare trade data from endpoint and txhash from https://algoexplorer.io/
      - If not enough balance, getting error of `overspend` both client and gateway logs 
      - If not approved  `receiver error: must op-tin`, asset 123456 missing from PZLY....UPZI, after opt-in request is resolved
      - Failed to trade with error (Trade query failed) when using pairs that cointain lowkey letters (goBTC, goETH, USDt etc.) ❌
      
 - Client + Gateway: Failed to start strategy using pairs with lowkey letters (goBTC, goETH, USDt etc.) ❌

**Review by nikspz — APPROVED** [review]
Test performed:
  Test on local WSL ubuntu20.04 with https://github.com/hummingbot/hummingbot/pull/6277
- Connect successfully wallet using `Pera wallet` seed phrase, correct balance displayed
- Ran test endpoints using curl
   - Status and /connectors ✅ 
   - /network/status?chain=algorand ✅ 
   - /wallet/add and /wallet/remove ✅ 
   - Get balance ✅ 
   - Get poll ✅ 
   - Get assets ✅ response with list of assets (GOBTC there use capital letters)
   - Post opt-in ✅  
   - Check prices ✅  
   - Trade {BUY,SELL} ✅ 
      - Compare trade data from endpoint and txhash from https://algoexplorer.io/
      - If not enough balance, getting error of `overspend` both client and gateway logs 
      - If not approved  `receiver error: must op-tin`, asset 123456 missing from PZLY....UPZI, after opt-in request is resolved
 - Client + Gateway: reported issue on PR6277

   Note: 
   - Current `Tokenlist(AssetList for algorand) is using remote URL (not local file)`
   - Gateway connector-tokens for this connector must be added on all uppercase, sample `GOBTC`
   - Failed to trade with error (Trade query failed) when using pairs that cointain lowkey letters (goBTC, goETH, USDt etc.)

**Review by fengtality — APPROVED** [review]

**Comment by nikspz** [comment]
Merged the PR in behalf of foundation team to development and will be available on the next version 1.16.0

**Pull request merged**
