### PR TITLE
Uniswap - add CELO chain/network to the current Uniswap connector

### PR DESCRIPTION
**Pull request by elijahsnoz**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:
Test performed:

Set up gateway successfully
connected uniswap ethereum celo successfully
check wallet now showing on gateway connect command
check gateway balance show balance for the ethereum cello wallet
curl

- [x] chain/status: ok
- [x] /chain/balances
- [x] add/ remove wallet: ok
- [x] /amm/price: ok

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
- Test performed:
    - Cloned and installed gwPR313 and development latest Client
    - gateway generate certs and make sure gateway ONLINE
    - /wallet/add: ok
    - amm/price: could check price succesfully, but price could be strange for some tokens (also same for uniswap site app prices)
    - amm/trade: Failed to trade CELO-USDC: "Error: Unsupported trade object
    - amm/trade: Failed to trade SUSHI-USDC: "Trade query failed: priceSwapOut: no trade pair found for 0xcebA9300f2b948710d2653dD7B07f33A8B32118C to 0x29dFce9c22003A4999930382Fd00f9Fd6133Acd1."
    

    
image
image
image
image

    
Note: CELO prices on celoscan and uniswap could not match. 

image
image


Note: on celoscan there're 5 USDC tokens with same ticker so you have to modify tokenlist before start

image

**Comment by elijahsnoz** [comment]
i will look into this and give a feedback @nikspz

**Comment by elijahsnoz** [comment]
changes have been made @nikspz

**Comment by nikspz** [comment]
@elijahsnoz 

commit 1231296

Test performed:

cloned gwPR313 and development hummingbot client
connected gateway successfully
gateway connector-tokens added USDC and cETH
gateway balance - Failed to check USDC balance (and cETH balance as well)
price_uniswap - failed to check the price


image
image

image
image


Also, shoud it be celo chain as well?

https://celoscan.io/address/0x08940dc9b5a19fab9319b77c61dda7b8067e6843#tokentxns

**Comment by elijahsnoz** [comment]
Updated the token list. @nikspz, it doesn't need to be on the Celo chain since Celo is EVM compatible.

**Review by fengtality — CHANGES_REQUESTED** [review]
Celo should be added as a separate chain, not a network, since it is a L1 chain.

If you don't have the experience to do so, please decline the bounty and we'll assign it to another dev.

**Comment by elijahsnoz** [comment]
Sorry, I must have received incorrect information. I noticed that some separate EVM chains were extended from Ethereum also noticed other devs on similar project built on ethereum. Thank you for the clarification. I will proceed with adding Celo as a separate chain.

**Comment by elijahsnoz** [comment]
i did like to give a short @fengtality

**Comment by elijahsnoz** [comment]
I refactored the code at @fengtality  with Celo as a separate chain.

**Comment by nikspz** [comment]
Failed to check balance using `gateway balance`

Steps:
1. Clone development + gwPR313
2. connect 

[logs_hummingbot.log](https://github.com/user-attachments/files/15570176/logs_hummingbot.log)

```
2024-06-04 20:37:48,682 - 4054695 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/nikita/d2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 524, in _get_balances
    bal_resp = await asyncio.wait_for(
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 718, in all_balances_all_exc
    await self.update_exchange(client_config_map)
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 713, in update_exchange
    results = await safe_gather(*tasks)
  File "/home/nikita/d2/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 673, in update_exchange_balances
    return await self.add_gateway_exchange(exchange_name, client_config_map, **api_keys)
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 649, in add_gateway_exchange
    market = GatewayCommand.connect_markets(
  File "/home/nikita/d2/hummingbot/client/command/gateway_command.py", line 602, in connect_markets
    connector_class = get_connector_class(exchange)
  File "/home/nikita/d2/hummingbot/client/config/config_helpers.py", line 563, in get_connector_class
    mod = __import__(conn_setting.module_path(),
  File "/home/nikita/d2/hummingbot/client/settings.py", line 214, in module_path
    return f"hummingbot.connector.{self.module_name()}"
  File "/home/nikita/d2/hummingbot/client/settings.py", line 204, in module_name
    return f"gateway.{self.type.name.lower()}.gateway_{connector_spec['chain_type'].lower()}_{self._get_module_package()}"
TypeError: 'NoneType' object is not subscriptable
```

image
[logs_hummingbot.log](https://github.com/user-attachments/files/15570194/logs_hummingbot.log)

image

**Comment by elijahsnoz** [comment]
since it is a new chain it has to be included in supported chain constant on client @nikspz 

Screenshot 2024-06-04 at 23 56 02

Screenshot 2024-06-05 at 00 00 11

would you like me to create a pr for that on client?

**Comment by nikspz** [comment]
> would you like me to create a pr for that on client?

ofc, if needed please proceed with it

**Comment by elijahsnoz** [comment]
https://github.com/hummingbot/hummingbot/pull/7073

**Comment by nikspz** [comment]
Test performed:
- Clone gatewayPR313 + PR7073
- Connected gateway uniswap celo celo
- Checked balance successfully
- approved WETH and USDC successfully
- created amm_arb using uniswap_celo_celo
- started amm_arb, got Error: WETH, token not supported


[logs_conf_amm_arb_1.log](https://github.com/user-attachments/files/16020918/logs_conf_amm_arb_1.log)
[gw313.zip](https://github.com/user-attachments/files/16020940/gw313.zip)

image

**Comment by elijahsnoz** [comment]
there was another weth in token list, removal of that should fix that @nikspz

**Comment by fengtality** [comment]
Thanks for the work @elijahsnoz. I'm making some updates to the Uniswap connectors so that other PRs can be merged in. I'll address the conflicts in this one afterwards and see if I can get it over the line.

**Comment by elijahsnoz** [comment]
Thank you, @fengtality   I'm glad I could help.

**Comment by fengtality** [comment]
Incorporated into #342

**Pull request closed without merging**
