### PR TITLE
Feat/injective perpetual

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces the Injective Perpetual Gateway connector.

**Tests performed by the developer**:

- Unit tests added for the new code.
- Manually tested the functionality.

**Tips for QA testing**:

Please test that the newly introduced endpoints for the clob perpetual Injective connector work as expected.

Link to client PR: https://github.com/hummingbot/hummingbot/pull/6200
Link to PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x1e36039ae9ff72c133b2bcf4e7c3aa66b25693b195ac3e5c31ab7fe3f813d745

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @petioptrv, good day to you. Would it be possible to know the next possible update? Thank you 🙇🏼

**Comment by petioptrv** [comment]
Hi @rapcmia, I'll look into all this right now

**Comment by petioptrv** [comment]
@rapcmia, I've pinged the Injective team for assistance with the trading pairs anomaly. I suspect that Helix is filtering out those pairs for some reason.

Also, I pushed the missing json file in [this](https://github.com/hummingbot/gateway/pull/81/commits/33e3c71e50b3b206c70e9578f4410c20fadd6a46) commit.

Tagging @vic-en

**Comment by petioptrv** [comment]
@rapcmia, I've received confirmation from the injective team that this is a decision that they've made to exclude those markets from the Helix app. They are, however, still available to trade on the injective chain.

**Comment by nikspz** [comment]
Hi @petioptrv , upon checking `get orders`, and `delete PERP` commands not fixed yet (no commit was provided to fix the issue)

I did some initial tests:
 
for INJ-USDT was able to place buy order to OPEN, failed to place sell order (bot can't see INJ balance maybe)
also successfully refreshing buy orders to OPEN (no stuck orders on exchange)
successfully cancelled buy order to OPEN after stop command

for ETH-USDT bot don't place any order to OPEN, no buy/sell order

**Comment by petioptrv** [comment]
@nikspz, the `get` and `delete` were added after-the-fact via comment edit. We will be addressing those today. 

> for INJ-USDT was able to place buy order to OPEN, failed to place sell order (bot can't see INJ balance maybe)
This is normal. The INJ/USDT PERP contract is collateralized in USDT, so the USDT balance is the only one that counts here. If most of the balance was used to create the long position open order, then there may have not been sufficient USDT for the short position open order. The logs reflect that.

> for ETH-USDT bot don't place any order to OPEN, no buy/sell order
USDT should be the collateral here too. There were no attempts to place orders on two of the runs... This seems to me like Perp MM is deciding not to place orders, but logs are missing to clarify why. Have you tried using another strategy here or reducing the order size? If this persists, I can add debug statements in Perp MM to see why it decides not to place orders.

**Comment by petioptrv** [comment]
@rapcmia, actually, the market ID, in this case, is the hash of the INJ/USDT PERP market. I don't think you can see the order has (order ID) using this approach. You can use the get command though.
```bash
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT "https://localhost:15888/clob/perp/orders?chain=injective&network=mainnet&connector=injective_perpetual&market=INJ-USDT&address=$INJECTIVE_SUBACCOUNTID"
```
This will give you all orders for the account and market up to a certain number of orders. You can get the `orderHash` from that information. This will work for both `get` and `delete`.

**Comment by nikspz** [comment]
@petioptrv 

got orders lost events during the bot run again, usually lost after 



```
ERROR - Unhandled error in background task: <AioRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "object not found"details = "object not found"
```


Tried to test Client side, set up tight spreads to OPEN/CLOSE position firstly was able to OPEN and CLOSE few positions according or close to take profit (0.2)/ stop loss(0.15) spread set up:

image
 
 
 [injper04.18.2023.zip](https://github.com/hummingbot/gateway/files/11265469/injper04.18.2023.zip)
[logs_injper1804.log](https://github.com/hummingbot/gateway/files/11265472/logs_injper1804.log)

Then I ran client little bit and its stuck with creating stop loss 😬
restarted the bot, bot was able to retrieve position 👍
and created/fill order to CLOSE position ( closed with price was worse then set up by strategy)
but after order refresh time created `only buy order to OPEN`
then after bot stopped, `order stuck on the exchange` 🙄

image


tried another strategy, 
bot is trying place 2 orders to OPEN, 
return Unhandled error in background task: No update for order for sell OPEN order. 
then after order refresh time bot tries to cancel sell OPEN order, but there's no order on the exchange

https://www.loom.com/share/1ab64c35055243599d4a06be17140e7c

**Comment by petioptrv** [comment]
The above issues have been [addressed in the client PR](https://github.com/hummingbot/hummingbot/pull/6200#issuecomment-1514998265).

**Review by fengtality — APPROVED** [review]
LGTM - I will add a commit after this is merged to create a new CLOB Perp section in Swagger docs

**Pull request merged**
