### PR TITLE
(feat) Sepolia testnet support on Uniswap connector

### PR DESCRIPTION
**Pull request by ndeporzio**
**Before submitting this PR, please make sure**:
            - [x] Your code builds clean without any errors or warnings
            - [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
            Added support for the Ethereum Sepolia testnet on Uniswap connector. Also included an initial token list.

### CODE REVIEW

**Comment by ndeporzio** [comment]
[hummingbot/hummingbot#6951](https://github.com/hummingbot/hummingbot/issues/6951)

**Comment by fengtality** [comment]
The changes look good, but I think the dev should also change the tests from Goerli to Sepolia as part of this fix.

**Comment by fengtality** [comment]
This PR needs more work. To complete this bounty, the dev should ensure that the Uniswap tests (which currently use Goerli) are modified to work on Sepolia using Sepolia test tokens. Currently, they are failing.

However, this may be difficult since there doesn't seem to be any tokens that trade on Uniswap Sepolia. It might make more sense to convert the unit tests to use Base.

**Comment by fengtality** [comment]
I added Sepolia support in https://github.com/hummingbot/gateway/pull/329, but the tests haven't yet been updated to use it, so the bounty is still available for any dev who wants to update the Ethereum and Uniswap tests for Sepolia

**Pull request closed without merging**
