### PR TITLE
feat/carbondefi

### LINKED ISSUE #255: feat/carbondefi - Add Carbon DeFi AMM and CLOB_SPOT connector
**Impact**

The desired behaviour is to add new DeFi primitives supported by Carbon DeFi that will expand the on-chain capabilities of Hummingbot Gateway and benefit the Hummingbot users with on-chain limit orders, and a new AMM connection/liquidity source. 

CarbonDeFi is a decentralised protocol live on Ethereum mainnet with similar deployments on Base, Mantle, Canto, Arbitrum, and Fantom which can be supported in the future, and supports any ERC-20 token (sans fee-on-transfer and rebase tokens, etc). Carbon DeFi allows any user to:
1. Create on-chain one-sided BUY/SELL range and limit orders for a pair of ERC-20 tokens ("disposable strategy")
2. Create two on-chain connected BUY and SELL range and limit orders ("recurring strategy") for a pair of ERC-20 tokens. Each order in the strategy adds to the liquidity of the other when selling tokens at the range the user selects.
3. Trade against any on-chain orders to obtain the best price execution (calculated by the Carbon DeFi SDK).
4. Future functionality with other types of strategies coming soon.

For this integration, supporting 1 and 3 works by creating an AMM connector and a CLOB_SPOT connector. A user can then trade against Carbon DeFi orders and create an on-chain limit order, which is executed against other exchanges on-chain via the [Arb Fast Lane](url)

**Feature Suggestion**

Add an AMM Carbon DeFi Connector that exposes the following endpoints:
- `/amm/price`
- `/amm/trade`
- `/amm/estimateGas`

and a CLOB_SPOT Carbon DeFi Connector that exposes the following endpoints:
- `clob/markets`
- `clob/orderBook`
- `clob/ticker`
- `clob/orders`
- `clob/estimateGas`

**Additional context**

Carbon DeFi documentation: https://docs.carbondefi.xyz

Example of some orders currently live on Carbon DeFi for the ETH-DAI pair (accessible through the [explorer](https://app.carbondefi.xyz/explorer/token-pair/eth_dai)):

Screenshot 2023-12-18 at 17 29 07

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
Closes #255 

**A description of the changes proposed in the pull request**:

In this pull request, a Carbon DeFi AMM connector is added. The following endpoints are available:

- Functions to expose in the gateway
	- AMMish
		- amm/trade POST
		- amm/price POST
		- amm/estimateGas POST
	- Generic
		- connectors GET
		- chain/tokens GET

**Tests performed by the developer**:

Test for Carbonamm
- Carbon constructor
- estimateSellTrade 
	- with possible trade path
	- without possible trade path
- estimateBuyTrade
	- with possible trade path
	- without possible trade path
- getAllowedSlippage
	- non-null input
	- null input
	- malformed input
- POST amm/price 
	- SELL side
		- valid parameters
		- invalid parameters
	- BUY side
		- valid parameters
		- invalid parameters
- POST amm/trade 
	- BUY side
		- valid parameters
		- invalid parameters
	- SELL side
		- valid parameters
		- invalid parameters
		- changing maxFeePerGas
- Creating the connector with unsupported chain
- Malformed allowedSlippage
	- in the request amm/trade
	- in the carbon.conf file

Coverage:

| File | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line |
| ----------------- | ----- | ----- | ----- | ----- | ------- |
| connectors/carbon | 98.53 | 90 | 98.52 | 99.69 |         |
| carbon.config.ts  | 100   | 100   | 100   | 100   |         |
| carbon.utils.ts   | 100   | 97.29 | 100   | 100   | 100      |
| carbonAMM.ts      | 100   | 100   | 100   | 100   |         |

**Tips for QA testing** and comments/questions:

- If using a private RPC, you can go to https://app.carbondefi.xyz/debug and input it there, then use the app to observe reflected changes coming from interacting with the gateway.
- The CarbonSDK is used, which can be found at https://github.com/bancorprotocol/carbon-sdk
- Both connectors initiate a cache and keep it up to date by polling events
	- The Carbon CLOB connector purposely hits the miss cache handler on initialisation to get all the on-chain information as it is a pre-requisite for the functionality of most CLOB endpoints
	- The Carbon AMM syncs in the background and can handle /price and /trade requests and hit cache miss handle
- jest.config.js modification - problem with jest not supporting subpath imports and exports pre version v29.4.0. Hummingbot gateway is currently using version 27.3.1. A workaround by modifying the jest.config file to manually add the subpath imports was used.

### CODE REVIEW

**Review by fengtality — CHANGES_REQUESTED** [review]
Requested changes:

- Please move all tests to the `test-bronze` folder, so that they are not included in workflows

- I think this PR should only add the AMM connector initially, since each connector requires an NCP. Keep in mind that DEX connectors are only meant to be standard integrations that work with a specific strategy, like AMM-ARB.

- I think the CLOB functionality, limit orders support, and associated endpoints could be part of this connector or as part of a different connector folder - it's up to how you want this connector to be used. Currently, Gateway assumes that these connectors are being added so that users can run standard strategies like AMM-ARB with them. However, if you want to add custom scripts that allow users to use other endpoints that this connector supports, that approach could work too.

**Comment by tiagofilipenunes** [comment]
Thank you for the review Michael. Changes:

- [x] Move tests to test-bronze
- [x] PR only adds AMM connector
- [x] Split CarbonAMM and CarbonCLOB into two separate PRs (CarbonCLOB implementation is currently at https://github.com/bancorprotocol/hummingbot-gateway/tree/tiagofilipenunes-feat/carbonclob)
- [x] Modify amm/trade and amm/price endpoints to support native ETH swapping for Carbon

**Comment by fengtality** [comment]
> Thank you for the review Michael. Changes:
> 
> * [x]  Move tests to test-bronze
> * [x]  PR only adds AMM connector
> * [x]  Split CarbonAMM and CarbonCLOB into two separate PRs (CarbonCLOB implementation is currently at https://github.com/bancorprotocol/hummingbot-gateway/tree/tiagofilipenunes-feat/carbonclob)
> * [x]  Modify amm/trade and amm/price endpoints to support native ETH swapping for Carbon

Looks good @tiagofilipenunes. I think you should be able to create a Pull Request Proposal to have us review and merge this connector into the codebase.

**Comment by nikspz** [comment]
hi @tiagofilipenunes Please resolve branch conflicts and be informed that all PRs should use development branch and be pointed to `development` branch (not main or master)

https://hummingbot.org/developers/contributions/#checklist

**Comment by tiagofilipenunes** [comment]
@nikspz Thanks for pointing that out, just merged and resolved conflicts.


- [x] Did I create my branch from development?
- [x] Did I follow the correct naming convention for my branch?
- [x] Is my branch focused on a single main change?
- [x] Do all of my changes directly relate to this change?
- [ ] Did I rebase the upstream development branch after I finished all my work? Merged them
- [x] Did I write a clear pull request message detailing what changes I made?
- [ ] Did I get a code review?
- [ ] Did I make any requested changes from that code review?

**Review by fengtality — APPROVED** [review]

**Comment by fengtality** [comment]
As @rapcmia's tests are successful, I will merge this PR in so that other PRs can resolve any conflicts if needed.

**Pull request merged**
