### PR TITLE
Fix/ unhandled error when using USDC.e

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

-  "fix"

** after the latest merge for commit **

- you should remove USDC.E if added✅

❌ Setup connector-token command and add USDC.e or USDC.E  ❌

then

- [ ] Setup connector-token command and add USDC.e ✅
- [ ] Setup amm-arb with avalanche or uniswap arbitrum_one connector ✅
- [ ] Observe the display balance upon starting the amm-arb ✅

"refactor" **changes made**

"symbol":"USDC.E",
"symbol":"USDC.e",

**Tests performed by the developer**:

- [ ] Setup connector-token command and add USDC.e or USDC.E ❌ threw duplicate  

Screenshot from 2023-07-27 04-12-23

- [ ] Setup amm-arb with avalanche or uniswap arbitrum_one connector ✅
- [ ] Observe the display balance upon starting the amm-arb ✅

Screenshot from 2023-07-27 02-25-31

Screenshot from 2023-07-27 04-12-23

**Tips for QA testing**:

- [ ] Setup connector-token command and add USDC.e ✅
- [ ] Setup amm-arb with avalanche or uniswap arbitrum_one connector ✅
- [ ] Observe the display balance upon starting the amm-arb ✅

### CODE REVIEW

**Comment by isreallee82** [comment]
[Uniswap unhandled error and duplicate values for USDC.e on ui](https://github.com/hummingbot/gateway/pull/177/commits/045c8f52ec8025d144846e009a900e1bf2c178cd)

**Comment by nikspz** [comment]
I don't think changing arbitrum token list to `USDC.e` actually will fix the issue, since arbitrum was unable to trade using USDC.e before, but was okay with USDC.E. I will re-check this fix later

**Comment by isreallee82** [comment]
> I don't think changing arbitrum token list to `USDC.e` actually will fix the issue, since arbitrum was unable to trade using USDC.e before (this PR #133), but was okay with USDC.E. I will re-check this fix later

alright please do

**Comment by nikspz** [comment]
I guess previous changes in #133 was related we used rate oracle for calculation, current version had PR updates for not to use it https://github.com/hummingbot/hummingbot/pull/6472 (rate_oracle_enabled is False by default)

Test performed using rate_oracle_enabled False, successful trades:
image

**Comment by nikspz** [comment]
Test performed:
Cloned and install fix branch + latest development branch
gateway connect uniswap_arbitrum_one
Setup simple AMM arb and observed expected behavior, filled trades when setting market `USDC.e` for `arbitrum`_one and binance paper trade as 2nd connector ✅

image

Setup simple AMM arb and observed the same error as Ralph mentioned in the #143  when setting market USDC.E for arbitrum_one, and binance_paper_trade as 2nd connector
 
image

**Comment by isreallee82** [comment]
Yes definitely it also resulting in the duplicates on the uiSent from my iPhoneOn 27 Jul 2023, at 9:47 AM, nikspz ***@***.***> wrote:﻿
@isreallee82

Is that nessasary change?

**Comment by isreallee82** [comment]
I am sure your frontend developer would agree, cos the contract must have been deployed as USDC.eSent from my iPhoneOn 27 Jul 2023, at 10:04 AM, isreal lee ***@***.***> wrote:﻿Yes definitely it also resulting in the duplicates on the uiSent from my iPhoneOn 27 Jul 2023, at 9:47 AM, nikspz ***@***.***> wrote:﻿
@isreallee82

Is that nessasary change?

**Comment by isreallee82** [comment]
> Yes definitely it also resulting in the duplicates on the uiSent from my iPhoneOn 27 Jul 2023, at 9:47 AM, nikspz ***@***.***> wrote:﻿ @isreallee82 Is that nessasary change? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

That must be a typo

**Comment by isreallee82** [comment]
I noticed the latest changes are trying to merge with the current pr I hope that doesn’t mean anything

**Comment by nikspz** [comment]
@isreallee82 Could you revert changes related to the changing `arbitrum_one` to `arbitrum`?

**Comment by isreallee82** [comment]
@nikspz  alright i willdo that

**Comment by isreallee82** [comment]
@nikspz please can you confirm if  I did the right thing

**Comment by nikspz** [comment]
yes @isreallee82

**Review by nikspz — APPROVED** [review]
Checked previous commit on the PR, same changes 
Test performed:

- Cloned and installed feature branch and latest development
- bot was able to trade using WETH-USDC.e
- the error/warning message that happened on USDC.E usage (development branch) not happened for me on this branch (changes to USDC.e)

NOTE: with these changes it will fail to trade with USDC.E then (getting exactly same issue reported in https://github.com/hummingbot/gateway/issues/143)
However default token in arbitrum has name USDC.e so I think it's correct to change
https://arbiscan.io/token/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8
image

**Comment by nikspz** [comment]
@isreallee82 Could you please fix the conflicts?

**Comment by isreallee82** [comment]
alright @nikspz on that

**Pull request merged**
