### PR TITLE
Feat / Add Uniswap on chains BSC, Avalanche, and Celo

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

* Adds Uniswap support for Binance Smart Chain, Avalanche, and Celo, refactored from community PRs
* Fixes tests

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by fengtality** [comment]
@nikspz this PR should be ready for testing. i'll incorporate the Avalanche Uniswap PR into this one as well, so that you can test both.

**Comment by nikspz** [comment]
@fengtality @harjas27 @isreallee82 
Test performed:
- Cloned and installed gwPR342 + Client PR https://github.com/hummingbot/hummingbot/pull/7073
- connected uniswap_avalanche_avalanche, uniswap_celo_celo, uniswap_bsc_mainnet successfully
- checked gateway balance for uniswap_avalanche_avalanche, uniswap_celo_celo, uniswap_bsc_mainnet successfully
- added connector-tokens WAVAX,USDC to uniswap_avalanche_avalanche successfully
- added connector-tokens WBNB,USDT to uniswap_bsc_mainnet successfully
- added connector-tokens to uniswap_celo_celo successfully
- Curl:
    - uniswap_bsc_mainnet
        - wallet/add: ok
        - amm/price: ok
        - chain/approve: ok
        - amm/trade: Failed, on default and 2 different public nodes
    - uniswap_avalanche_avalanche
        - wallet/add: ok
        - amm/price: ok
        - amm/trade: Failed
    - uniswap_celo_celo
        - wallet/add: ok
        - amm/price: ok
        - amm/trade: Failed


Avalanche trade failed:

```
{
  "message": "Unknown error.",
  "httpErrorCode": 503,
  "errorCode": 1099,
  "stack": "Error: Unsupported trade object\n    at Function.encodeSwaps (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:1992:15)\n    at Function.swapCallParameters (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:2023:44)\n    at Uniswap.<anonymous> (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:227:62)\n    at Generator.next (<anonymous>)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:4:12)\n    at Uniswap.executeTrade (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:226:16)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.controllers.js:132:41\n    at Generator.next (<anonymous>)"
}

```
image

Celo trade failed:

```
{
  "message": "Unknown error.",
  "httpErrorCode": 503,
  "errorCode": 1099,
  "stack": "Error: Unsupported trade object\n    at Function.encodeSwaps (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:1992:15)\n    at Function.swapCallParameters (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:2023:44)\n    at Uniswap.<anonymous> (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:227:62)\n    at Generator.next (<anonymous>)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:4:12)\n    at Uniswap.executeTrade (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:226:16)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.controllers.js:132:41\n    at Generator.next (<anonymous>)"
}

```


BSC trade failed:

```
{
  "message": "Unknown error.",
  "httpErrorCode": 503,
  "errorCode": 1099,
  "stack": "Error: Unsupported trade object\n    at Function.encodeSwaps (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:1992:15)\n    at Function.swapCallParameters (/home/hummingbot/gwbsc/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:2023:44)\n    at Uniswap.<anonymous> (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:227:62)\n    at Generator.next (<anonymous>)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:4:12)\n    at Uniswap.executeTrade (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.js:226:16)\n    at /home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.controllers.js:132:41\n    at Generator.next (<anonymous>)"
}
```
image
image
image

**Comment by fengtality** [comment]
@nikspz Can you test executing a Uniswap swap on `development` branch on:
* Polygon Mainnet
* Ethereum Arbitrum
* Ethereum Optimism

I think this swaps issue exists on other networks on `development` branch as well. Still investigating.

**Comment by nikspz** [comment]
Development branch CLient + dev branch gateway:

(uniswap) Arbitrum:
- amm/price: ok
- amm/ trade: ok 

(uniswap) Polygon:
- amm/ trade: ok 

(uniswap) Optimism
- amm/ trade: ok


trades:
https://arbiscan.io/tx/0xdfca5bbceb780424e98462ae361ffaa5c2837de642843552d0f17ec20340be2e
https://optimistic.etherscan.io/tx/0xc35dcfe900d85a599685e9b04b67f921826aafd2f002266080a8ad049d9f0ba1
https://polygonscan.com/tx/0xc347c427eab9786b15955a1c2584acf5bc5d357ede3f2a437287ddcd90341b85

arbitrum

image
image

polygon

image

optimism

image

**Comment by fengtality** [comment]
The issue is that upgrading Uniswap swap order router above 3 breaks swaps on all Uniswap connectors. 

However, not upgrading it results in the following error when fetching price on BSC:

```
"stack": "Error: No address for Uniswap Multicall Contract on chain id: 56\n    at new UniswapMulticallProvider (/Users/feng/gateway/node_modules/@uniswap/smart-order-router/build/main/providers/multicall-uniswap-provider.js:30:19)\n    at new AlphaRouter (/Users/feng/gateway/node_modules/@uniswap/smart-order-router/build/main/routers/alpha-router/alpha-router.js:47:97)\n    at new Uniswap (/Users/feng/gateway/dist/src/connectors/uniswap/uniswap.js:64:33)\n    at Uniswap.getInstance (/Users/feng/gateway/dist/src/connectors/uniswap/uniswap.js:90:51)\n    at /Users/feng/gateway/dist/src/services/connection-manager.js:134:51\n    at Generator.next (<anonymous>)\n    at /Users/feng/gateway/dist/src/services/connection-manager.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/feng/gateway/dist/src/services/connection-manager.js:4:12)\n    at getConnector (/Users/feng/gateway/dist/src/services/connection-manager.js:131:12)"
```

I think this PR needs more work to figure out how to add support for Uniswap on other chains. Perhaps upgrading from using Swap Router 2 to Universal Router is needed.

**Comment by fengtality** [comment]
@nikspz I added a hacky fix, so I think Uniswap swaps should now work on BSC, Avalanche, and Celo.

**Comment by nikspz** [comment]
0cac4ea
- arbitrum
   - amm/price: ok
   - amm/trade: ok
 - BSC mainnet
   - amm/price: ok
   - amm/trade: ok
 - Avalanche
   - amm/price: ok 
   - amm/trade: ok
 - Celo
   - amm/price: ok 
   - amm/trade: ok

BSC mainnet
price
image
trade
image
https://bscscan.com/tx/0xd5305cea3199544ab3d5f8e392f86cbd4f3e9ad3106cd5e14fff64bccdff4896

avalanche_avalanche
price
image
trade
https://snowtrace.io/tx/0xdda13d5aa26cfe566e5918fa2218a6a0957d1f0c63a33c3fd8536f051d04ce06


celo
price
image

trade
https://celoscan.io/tx/0x6403f92cbb4f407c5b2be3f3b2026e36c2b6d5c88a416f795e4ca767e4ac891b
https://celoscan.io/tx/0xa8824f6420fd2df84d7fc34bcb9407c636f50ddeb58811a427dffe25fb773f5d

**Comment by nikspz** [comment]
Failed to add uniswapLP for BSC mainnet, avalanche avalanche, connector (works for Celo)

Steps:
1. start the client with gateway set up
2. connect uniswapLP avalanche
3. failed to connect for connected and for new wallet



```
2024-07-29 19:14:20,877 - 145951 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/chain/balances failed. See logs for more details.
2024-07-29 19:14:20,878 - 145951 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: No address for Uniswap Multicall Contract on chain id: 43114\n    at new UniswapMulticallProvider (/home/hummingbot/gwbsc/node_modules/@uniswap/smart-order-router/build/main/providers/multicall-uniswap-provider.js:30:19)\n    at new AlphaRouter (/home/hummingbot/gwbsc/node_modules/@uniswap/smart-order-router/build/main/routers/alpha-router/alpha-router.js:47:97)\n    at new UniswapLPHelper (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.helper.js:76:33)\n    at new UniswapLP (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.js:44:9)\n    at UniswapLP.getInstance (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.js:52:53)\n    at /home/hummingbot/gwbsc/dist/src/services/connection-manager.js:137:56\n    at Generator.next (<anonymous>)\n    at /home/hummingbot/gwbsc/dist/src/services/connection-manager.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/hummingbot/gwbsc/dist/src/services/connection-manager.js:4:12)'}
Traceback (most recent call last):
  File "/home/hummingbot/dev2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/dev2/hummingbot/client/command/gateway_command.py", line 369, in _gateway_connect
    balances: Dict[str, Any] = await self._get_gateway_instance().get_balances(
  File "/home/hummingbot/dev2/hummingbot/core/gateway/gateway_http_client.py", line 293, in get_balances
    return await self.api_request(
  File "/home/hummingbot/dev2/hummingbot/core/gateway/gateway_http_client.py", line 222, in api_request
    raise e
  File "/home/hummingbot/dev2/hummingbot/core/gateway/gateway_http_client.py", line 210, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: No address for Uniswap Multicall Contract on chain id: 43114\n    at new UniswapMulticallProvider (/home/hummingbot/gwbsc/node_modules/@uniswap/smart-order-router/build/main/providers/multicall-uniswap-provider.js:30:19)\n    at new AlphaRouter (/home/hummingbot/gwbsc/node_modules/@uniswap/smart-order-router/build/main/routers/alpha-router/alpha-router.js:47:97)\n    at new UniswapLPHelper (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.helper.js:76:33)\n    at new UniswapLP (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.js:44:9)\n    at UniswapLP.getInstance (/home/hummingbot/gwbsc/dist/src/connectors/uniswap/uniswap.lp.js:52:53)\n    at /home/hummingbot/gwbsc/dist/src/services/connection-manager.js:137:56\n    at Generator.next (<anonymous>)\n    at /home/hummingbot/gwbsc/dist/src/services/connection-manager.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/hummingbot/gwbsc/dist/src/services/connection-manager.js:4:12)'}


```

image
image


Works for arbitrum:

image

**Comment by fengtality** [comment]
@nikspz thanks - i fixed the `uniswaplp` bug

**Comment by nikspz** [comment]
7e565d4
Test performed:
- Amm_arb strategy works for avalanche and BSC
- Curl:
  - arbitrum
     - amm/price: ok
     - amm/trade: ok
   - BSC mainnet
     - amm/price: ok
     - amm/trade: ok
     - amm/liquidity/add: ok
     - amm/liquidity/remove: ok
   - Avalanche
     - amm/price: ok 
     - amm/trade: ok
     - amm/liquidity/add: ok
     - amm/liquidity/remove: ok
   - Celo
     - amm/price: ok 
     - amm/trade: ok
- Amm_LP: created LP position succesffully: 
    - Unable to fetch pool state (avalanche, BSC)

Celo:

add position: ok
image
Remove: ok


BSC
add position - ok, position added, however failed to fetch status
https://bscscan.com/tx/0xf5fc4964726d7d02338413f8626a31d84350971bbd859a276d97028ef0b55f4e
image
image
image

remove position: ok
image

avalanche_avalanche

add position: ok Position created 
issue on amm_v3_LP, not sure if related to node. 
image

Remove position: ok
image

**Review by nikspz — DISMISSED** [review]

**Comment by nikspz** [comment]
amm/liquidity/position failed on curl as well, could be fixed in the next PR


image
image
image

**Comment by fengtality** [comment]
@nikspz I took a quick look at the `/amm/liquidity/position` issue but it requires more investigation. Looks like the position is successfully created but doing the tokenID lookup fails for some reason.

I suggest that we merge this PR in, and then I'll look at the LP functionality separately.

**Review by nikspz — APPROVED** [review]
merge this PR in, to look at the LP functionality separately.

**Pull request merged**
