### PR TITLE
Fix/uniswap token address

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR enables EVM connectors to store and query tokens using checksummed addresses.

**Tests performed by the developer**:
- Manual curl test on uniswap LP routes.

**Tips for QA testing**:
- Test all EVM(AMM/LP/Perp) connectors and confirm nothing is broken.
Thanks.

### CODE REVIEW

**Comment by vic-en** [comment]
Resolves issue reported on https://github.com/hummingbot/gateway/issues/154

**Comment by emusol** [comment]
I was able to add monitor and remove liquidity from a live position, but when the position was out of range I was not able to get info about the position:
image

**Comment by vic-en** [comment]
@emusol 
Can you send a screenshot of when the response of the request was successful?

**Review by fengtality — APPROVED** [review]

**Comment by rapcmia** [comment]
PR update:
- Setup this PR with latest development client 
- Setup AMM arb with uniswap {arbitrum, polygon}, pancakeswap-bsc and pangolin-avax
   - Start strategy and able to display no arb opportunity on logs 
   - Trade data on client and txn are ok too
   - However for Uniswap-Goerli:
      image
      ```
      2023-07-24 12:45:09,001 - 14731 - hummingbot.strategy.amm_arb.amm_arb - INFO - Markets are ready. Trading started.
      2023-07-24 12:45:10,365 - 14731 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.DivisionImpossible'>]
      Traceback (most recent call last):
        File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
          return await c
        File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/amm_arb/amm_arb.py", line 234, in main
          await self.apply_slippage_buffers(profitable_arb_proposals)
        File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/amm_arb/amm_arb.py", line 266, in apply_slippage_buffers
          arb_side.order_price = market.quantize_order_price(arb_side.market_info.trading_pair,
        File "hummingbot/connector/connector_base.pyx", line 471, in hummingbot.connector.connector_base.ConnectorBase.quantize_order_price
          return self.c_quantize_order_price(trading_pair, price)
        File "hummingbot/connector/connector_base.pyx", line 465, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
          return (price // price_quantum) * price_quantum
      decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
      ```    
       - This issue does not happen on development gateway branch 👀 
---
Run curl test on uniswapLP
- Add liquidity position ✅
   image
- Remove liquidity position ✅
   image

**Comment by vic-en** [comment]
> PR update:
> 
>     * Setup this PR with latest development client
> 
>     * Setup AMM arb with uniswap {arbitrum, polygon}, pancakeswap-bsc and pangolin-avax
>       
>       * Start strategy and able to display no arb opportunity on logs
>       * Trade data on client and txn are ok too ✅
>       * However for Uniswap-Goerli:
>         image
>         ```
>         2023-07-24 12:45:09,001 - 14731 - hummingbot.strategy.amm_arb.amm_arb - INFO - Markets are ready. Trading started.
>         2023-07-24 12:45:10,365 - 14731 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.DivisionImpossible'>]
>         Traceback (most recent call last):
>           File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
>             return await c
>           File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/amm_arb/amm_arb.py", line 234, in main
>             await self.apply_slippage_buffers(profitable_arb_proposals)
>           File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/amm_arb/amm_arb.py", line 266, in apply_slippage_buffers
>             arb_side.order_price = market.quantize_order_price(arb_side.market_info.trading_pair,
>           File "hummingbot/connector/connector_base.pyx", line 471, in hummingbot.connector.connector_base.ConnectorBase.quantize_order_price
>             return self.c_quantize_order_price(trading_pair, price)
>           File "hummingbot/connector/connector_base.pyx", line 465, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
>             return (price // price_quantum) * price_quantum
>         decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
>         ```
>         
>         
>             
>               
>             
>         
>               
>             
>         
>             
>           
>         
>         * This issue does not happen on development gateway branch 👀
> 
> 
> Run curl test on uniswapLP
> 
>     * Add liquidity position ✅
>       image
> 
>     * Remove liquidity position ✅
>       image

- Issue reported on Goerli testnet should be retested. I believe it has nothing to do with this pr.
 It's most-likely an issue with liquidity. Pls retest on a more liquid market on that testnet.

**Comment by fengtality** [comment]
I agree with @vic-en that the Goerli issue should be unrelated to this fix

**Review by rapcmia — APPROVED** [review]
LGTM

- Setup this PR with lates development client
- Setup DEX connectors `GOLD` and `SILVER` ok 
- Retest reporting issue on Goerli and confirm related to token used
- Ran curl tests for uniswapLP and able to add/remove position ok

**Comment by emusol** [comment]
I tried to test this a lot, and one issue keeps coming up, but not every time so I cant put my finger on it,
when monitoring a position and it goes out of range, some of the times gateway fails to fetch the position(also when retrying to get the position), but other times it get it right, for now I noticed it when watching a position for an hour before it goes out of range

[gateway log.txt](https://github.com/hummingbot/gateway/files/12165017/gateway.log.txt)

**Comment by vic-en** [comment]
> 

Looks like a node connection issue.
Request to fetch position timed out. Noticed that preceding request to update gasPrice also timedout.

Try swithing to a more stable and reliable node or package.

**Pull request merged**
