### PR TITLE
refactor: support sushiswap on polygon and mumbai network

### PR DESCRIPTION
**Pull request by gzliudan**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Support sushiswap on polygon and mumbai chain

**Tests performed by the developer**:

Start gateway:

```bash
yarn start --passphrase=daniel
```

---

Query network status of polygon:

```bash
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT "${SERVER}/network/status?chain=polygon&network=mainnet" | jq
```

---

Query network status of mumbai:

```bash
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT "${SERVER}/network/status?chain=polygon&network=mumbai" | jq
```

---

Query token list of polygon:

```bash
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT "${SERVER}/network/tokens?chain=polygon&network=mainnet" | jq
```

---

Query token list of mumbai:

```bash
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT "${SERVER}/network/tokens?chain=polygon&network=mumbai" | jq

```

---

Query sushiswap mumbai buy price:

```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/price" -d '{
    "connector": "sushiswap",
    "chain": "polygon",
    "network": "mumbai",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "BUY"
}' | jq
```

---

Query sushiswap mumbai sell price:

```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/price" -d '{
    "connector": "sushiswap",
    "chain": "polygon",
    "network": "mumbai",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "SELL"
}' | jq
```

---

Add private key:

```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/wallet/add" \
-d '{"privateKey":"'"${ETH_PRIVATE_KEY}"'","chain":"polygon","network":"mainnet"}' | jq

curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/wallet/add" \
-d '{"privateKey":"'"${ETH_PRIVATE_KEY}"'","chain":"polygon","network":"mumbai"}' | jq

```

---

Trade of mumbai sushiswap buy:

```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/trade" -d '{
    "address": "'"$ETH_ADDRESS"'",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "BUY",
    "chain": "polygon",
    "network": "mumbai",
    "connector": "sushiswap"
}' | jq
```

---

Trade of mumbai sushiswap sell:

```bash
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/trade" -d '{
    "address": "'"$ETH_ADDRESS"'",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "SELL",
    "chain": "polygon",
    "network": "mumbai",
    "connector": "sushiswap"
}' | jq
```

---

Test on client with command `gateway connect sushiswap`:

**Tips for QA testing**:

1. Add below tokens to file `src/chains/polygon/polygon_tokens_mumbai.json` before run `yarn build`:

```json
    {
      "symbol": "WBTC2",
      "chainId": 80001,
      "address": "0x04597a1486b4F9d8284A4771703C1808D2a29b81",
      "decimals": 8
    },
    {
      "symbol": "YFI2",
      "chainId": 80001,
      "address": "0xa79391e7B2b48a4Eb7F2228ef625a32716eE4E93",
      "decimals": 18
    },
    {
      "symbol": "MKR2",
      "chainId": 80001,
      "address": "0xc16d215c621bbfd12999c9f456dab44db755ddd5",
      "decimals": 18
    },
    {
      "symbol": "AAVE2",
      "chainId": 80001,
      "address": "0x34006a403f5aba9f247a284e6278fbcb7c00df38",
      "decimals": 18
    },
    {
      "symbol": "UNI2",
      "chainId": 80001,
      "address": "0x0a696e15754f9de196a939fecb8c412812d5881d",
      "decimals": 18
    },
    {
      "symbol": "USDC2",
      "chainId": 80001,
      "address": "0xb6ae5ac95088f80f43a52f6be2b44906492b0d98",
      "decimals": 6
    }
```

---

2. Set the following environment variables:

```bash
export SERVER="https://127.0.0.1:15888"
export HEADER="Content-Type: application/json"
export ETH_ADDRESS="0xD4CE02705041F04135f1949Bc835c1Fe0885513c"
CERT=$(ls -Frt ${HOME}/.hummingbot-gateway | grep -E '^hummingbot-gateway-[0-9a-z]{8}/$' | tail -n 1)
export CERTS_PATH="${HOME}/.hummingbot-gateway/${CERT:0:-1}/certs"
export GATEWAY_CERT="${CERTS_PATH}/client_cert.pem"
export GATEWAY_KEY="${CERTS_PATH}/client_key.pem"
export ETH_PRIVATE_KEY=<MY_PRIVATE_KEY>
```

### CODE REVIEW

**Review by fengtality — APPROVED** [review]
LGTM. This should be passing coverage checks on `development` since I've lowered the coverage thresholds to 50%/60% for the time being.

**Comment by fengtality** [comment]
@gzliudan Sorry, can you please add manual `curl` scripts to allow users and QA to test the Sushiswap Polygon endpoints? See https://github.com/hummingbot/gateway/blob/main/test-helpers/curl/curl.sh for examples of Sushiswap scripts for other chains.

**Review by fengtality — CHANGES_REQUESTED** [review]
See above

**Comment by gzliudan** [comment]
@fengtality @rapcmia  Ok, it's done. I submit a new commit just now.

> @gzliudan Sorry, can you please add manual `curl` scripts to allow users and QA to test the Sushiswap Polygon endpoints? See https://github.com/hummingbot/gateway/blob/main/test-helpers/curl/curl.sh for examples of Sushiswap scripts for other chains.

**Review by rapcmia — APPROVED** [review]
LGTM

- Setup development client + this PR using source setup
- gateway list displays Sushiswap with support on Polygon chain
- gateway connect sushiswap now supports polygon mainnet/mumbai
- Ran all curl commands as advised, all ok

**Pull request merged**
