### PR TITLE
(feat) pancakeswap mainnet

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Added functionalities to enable interaction with Pancakeswap on the Ethereum mainnet.
Ensured compatibility and seamless integration with the existing Pancakeswap connector architecture.
Implemented appropriate handling for chain-specific differences and features.

**Tests performed by the developer**:
curl test

**Tips for QA testing**:
curl test

### CODE REVIEW

**Comment by isreallee82** [comment]
Good for a review now @nikspz

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed latest development branch and gwPR299
- Set up gateway successfully
- connected pancakeswap ethereum mainnet successfully
- check wallet now showing on gateway connect command
- check gateway balance show balance for the ethereum mainnet wallet
- curl
    - chain/status: ok
    - /chain/balances
    - add/ remove wallet: ok
    - /amm/price: ok

**Comment by isreallee82** [comment]
Good for a review now @nikspz

**Comment by isreallee82** [comment]
fixed @nikspz

**Comment by nikspz** [comment]
- commit [[e812844](https://github.com/hummingbot/gateway/pull/299/commits/e812844aeea76eb518f4b241bcf388073e0b691c)](https://github.com/hummingbot/gateway/pull/299/commits/e812844aeea76eb518f4b241bcf388073e0b691c)
    - Test performed:
        - cloned and installed development + gwPR299
        - connected pancakeswap_ethereum_arbitrum
        - check balance succesfully
        - ~~Failed to~~ approved token using `gateway approve-tokens pancakeswap_ethereum_arbitrum WETH`
            
image

      
image

        - created/started amm_arb strategy using pancakeswap_ethereum_arbitrum
            - price query failed: Cannot find a valid swap
image
      
pancake

**Comment by isreallee82** [comment]
sorry pancakeswap doc havent be updated, I see this have to do with subgraph api, I just noticed it was on their GitHub will push in a min @nikspz

**Comment by isreallee82** [comment]
that should solve the price query error @nikspz

**Comment by isreallee82** [comment]
I just change the endpoints to the second one provided @nikspz, also tested it against pairs on available on arbitrum network. https://pancakeswap.finance/info/v3/arb/pairs, https://pancakeswap.finance/info/v2/arb/pairs

**Comment by isreallee82** [comment]
what market pair are you using @nikspz

**Comment by nikspz** [comment]
> what market pair are you using @nikspz

WETH-USDC

**Comment by isreallee82** [comment]
With curl test all seem to work fine @nikspz can you try with last push.

**Comment by nikspz** [comment]
[logs_gateway_app.log.2024-04-09.log](https://github.com/hummingbot/gateway/files/14922716/logs_gateway_app.log.2024-04-09.log)
[logs_pancake-arb.log](https://github.com/hummingbot/gateway/files/14922737/logs_pancake-arb.log)


image



Curl:
- chain/tokens : ok
- amm/price: had instances when able to check price, then failing @isreallee82 
image

Note: Not usable for amm_arb, will discuss and check to finalize PR

**Comment by isreallee82** [comment]
Alright @nikspz, Also I guess the subgraph is api rate limited, made a clean-up on the pr for instances where chain is called to avoid lots of iteration, no change in functionality, I will await your feedback

**Review by fengtality — APPROVED** [review]

**Review by nikspz — APPROVED** [review]
- commit e7e3146
    - Connected zksync succesfully
    - connected arbitrum succesfully
    - added connector-tokens
    - checked pancakeswap gateway balance succesfully
    - amm/price shows price then Failed for amm_arb strategy after ~5-10 sec after start
    - curl
        - wallet/add
            - arbitrum, mainnet, zksync: ok
        - amm/price pancakeswap ethereum
            - arbitrum: ok
            - zksync: ok
            - mainnet: ok
        - amm/trade
            - arbitrum: ok
https://arbiscan.io/tx/0x75361012061d13c640babb649a2b8ac241558b51f15138566c5a9aa595db9e71
        - amm/liquidity/add: ok        https://arbiscan.io/tx/0x6a9fe1d7631ab17015dcb0d30697f5ebf2e261bc82d1cc933e860c4d3a539b8d


Note: There's still cases of amm/price failing when using amm_arb strategy using pancakeswap arbitrum

image

**Comment by rapcmia** [comment]
Merged to development and part of release version 1.27.0

**Pull request merged**
