### PR TITLE
Feat/dexalot

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This is the main pr for Dexalot gateway. The functionality of this connector can be accessed through the endpoints on the club routes combined with the endpoints on the network routes.

Hence, the qa should test the following endpoints:
```
/network/balances
/network/poll
/clob/markets
/clob/orderBook
/clob/ticker
[GET] /clob/orders
[POST] /clob/orders
[DELETE] /clob/orders
/clob/batchOrders
/clob/estimateGas
```

**Notes for QA**
The flow from creation to cancellation of orders is as follows:
- Create orders by making request to the `[POST] /clob/orders` or `/clob/batchOrders` with the createOrderParams. You will get a response similar to the one below
Screenshot 2023-03-10 at 1 50 45 AM
- Poll for the status of the transaction using the txHash in the response to know the status of the creation transaction.
- Once the transaction is confirmed, make a request to `[GET] /clob/orders` using your public key address and the ClientOrderId returned in the response to create orders. By doing this, you'll be able to see the id (i.e. exchangeOrderId)
- The id(i.e. exchangeOrderId) can then be supplied as the id to any of the cancellation endpoint to cancel the order.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Successfully setup this PR and https://github.com/hummingbot/hummingbot/pull/6153
- Tested some of endpoints on `Postman `and `Curl`
- https://localhost:15888 → connection ok
- https://localhost:15888/wallet/add → add wallet ok- 
-  https://localhost:15888/network/poll → poll ok
- https://localhost:15888/network/balances → `no go`

For `network/balances`. We are not able to get the balances which works ok when using other network such as `avalanche`, 
image
```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"balanceOf(address)\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Interface.decodeFunctionResult (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/abi/lib/interface.js:388:23)\n    at Contract.<anonymous> (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/home/rapcmia/github/gateway/65/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Setup CURL test and txhash can be found [here](https://subnets.avax.network/dexalot/address/0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843)
- /clob/markets ✅ 
- /clob/orderBook ✅ 
- /clob/ticker ✅ 
- [POST] /clob/orders ✅ 
- [GET] /clob/orders ✅ 
- [DELETE] /clob/orders ✅ 
- /clob/batchOrders
   - Create ✅ 
   - Delete ✅ 

For `clob/estimateGas`, we cant find it on the list. Would you be able to advise how we can test it? thank you

**Comment by rapcmia** [comment]
> For `network/balances`. We are not able to get the balances which works ok when using other network such as `avalanche`,

Got some help with colleagues with CA QA team and confirm we are missing the `connector: dexalot`. 
`network/balances` now working on postman

image

We can assume this PR is good for approval unless we have to wait for the dexalot API key prompt from the client side and retest again. Thank you 🙇

**Review by fengtality — DISMISSED** [review]
LGTM

@vic-en Some questions:

-  Currently, the EVMBroadcaster is only used to send Dexalot transactions. Should it be used for all EVM connectors?
- Where are the new wallet sign routes used?

**Comment by fengtality** [comment]
> Got some help with colleagues with CA QA team and confirm we are missing the connector: dexalot.
network/balances now working on postman

@vic-en Please add `connector` to the Swaggers docs for `/network/balances`

**Review by rapcmia — DISMISSED** [review]
LGTM

- Successfully setup this PR and https://github.com/hummingbot/hummingbot/pull/6153
- Gateway connection successful
- Ran Postman test on the following:
	- Connection, Status, Balances, Poll, Tokens and amm/estimateGas all ok 
- Ran Curl test on the following:
	- modified `injective `.json files to `dexalot` so we can test
	- /clob/markets
	- /clob/orderbook
	- /clob/ticker
	- {POST,GET,DELETE} /clob/orders
	- /clob/batchOrders
	- /clob/estimateGas 
		- Not available on curl.sh, `not tested`
- Check client, gateway list now shows dexalot {avalanche, BRONZE}

**Comment by fengtality** [comment]
@vic-en In the curl script JSON responses, the CLOB routes are still using Injective routes. Since Dexalot is a pure Gateway connector and a better example for other devs going forward, can you change them so that they are using the Dexalot routes?

**Comment by fengtality** [comment]
> 2. The new wallet sign route is used by the client to sign messages with the private key associated to the supplied public key.

What I mean is: why was this added? Where in the CLOB routes or Dexalot connector is this being used?

**Comment by vic-en** [comment]
> > 3\. The new wallet sign route is used by the client to sign messages with the private key associated to the supplied public key.
> 
> What I mean is: why was this added? Where in the CLOB routes or Dexalot connector is this being used?

The client makes some request to Dexalot api. As part of the authentication steps, a message needs to be signed using the wallet private keys. Hence, we had to create an endpoint for gateway to sign messages rather than sending the private key to the client. See - https://github.com/hummingbot/hummingbot/blob/f128526c643dec3d9996f60864f20e264409f17a/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_auth.py#L29

**Review by rapcmia — APPROVED** [review]

**Pull request merged**
